from leakageSadi import *
%logstart -o -r log1.py append
%time iLst = ImplicandLst(pLst, hLst);
%time fLst = getFinalList(iLst)
solver.push()
solver = z3.Solver()
solver.push()
for f in fLst:
    solver.add(f)
solver.push()
gEq5 = z3.AtLeast(nHandLst(5))
solver.add(gEq5)
%time solver.check()
#[Out]# sat
%magic
ls
%logstart -r -o -t gEq6Log.py append
%logstop
# Sun, 03 Dec 2017 23:39:15
gEq6 = z3.AtLeast(nHandLst(6))# Sun, 03 Dec 2017 23:39:28
len(solver.assertions())#[Out]# 167
# Sun, 03 Dec 2017 23:39:38
aL(solver.assertions()[-1])# Sun, 03 Dec 2017 23:39:46
aL = (solver.assertions())# Sun, 03 Dec 2017 23:39:49
aL[-1]# Sun, 03 Dec 2017 23:39:58
aL[166]#[Out]# AtMost((Not(h__0),
#[Out]#         Not(h__1),
#[Out]#         Not(h__2),
#[Out]#         Not(h__3),
#[Out]#         Not(h__4),
#[Out]#         Not(h__5),
#[Out]#         Not(h__6),
#[Out]#         Not(h__7),
#[Out]#         Not(h__8),
#[Out]#         Not(h__9),
#[Out]#         Not(h__10),
#[Out]#         Not(h__11),
#[Out]#         Not(h__12),
#[Out]#         Not(h__13),
#[Out]#         Not(h__14),
#[Out]#         Not(h__15),
#[Out]#         Not(h__16),
#[Out]#         Not(h__17),
#[Out]#         Not(h__18),
#[Out]#         Not(h__19),
#[Out]#         Not(h__20),
#[Out]#         Not(h__21),
#[Out]#         Not(h__22),
#[Out]#         Not(h__23),
#[Out]#         Not(h__24),
#[Out]#         Not(h__25),
#[Out]#         Not(h__26),
#[Out]#         Not(h__27),
#[Out]#         Not(h__28),
#[Out]#         Not(h__29),
#[Out]#         Not(h__30),
#[Out]#         Not(h__31),
#[Out]#         Not(h__32),
#[Out]#         Not(h__33),
#[Out]#         Not(h__34),
#[Out]#         Not(h__35),
#[Out]#         Not(h__36),
#[Out]#         Not(h__37),
#[Out]#         Not(h__38),
#[Out]#         Not(h__39),
#[Out]#         Not(h__40),
#[Out]#         Not(h__41),
#[Out]#         Not(h__42),
#[Out]#         Not(h__43),
#[Out]#         Not(h__44),
#[Out]#         Not(h__45),
#[Out]#         Not(h__46),
#[Out]#         Not(h__47),
#[Out]#         Not(h__48),
#[Out]#         Not(h__49),
#[Out]#         Not(h__50),
#[Out]#         Not(h__51),
#[Out]#         Not(h__52),
#[Out]#         Not(h__53),
#[Out]#         Not(h__54),
#[Out]#         Not(h__55),
#[Out]#         Not(h__56),
#[Out]#         Not(h__57),
#[Out]#         Not(h__58),
#[Out]#         Not(h__59),
#[Out]#         Not(h__60),
#[Out]#         Not(h__61),
#[Out]#         Not(h__62),
#[Out]#         Not(h__63),
#[Out]#         Not(h__64),
#[Out]#         Not(h__65),
#[Out]#         Not(h__66),
#[Out]#         Not(h__67),
#[Out]#         Not(h__68),
#[Out]#         Not(h__69),
#[Out]#         Not(h__70),
#[Out]#         Not(h__71),
#[Out]#         Not(h__72),
#[Out]#         Not(h__73),
#[Out]#         Not(h__74),
#[Out]#         Not(h__75),
#[Out]#         Not(h__76),
#[Out]#         Not(h__77),
#[Out]#         Not(h__78),
#[Out]#         Not(h__79),
#[Out]#         Not(h__80),
#[Out]#         Not(h__81),
#[Out]#         Not(h__82),
#[Out]#         Not(h__83),
#[Out]#         Not(h__84),
#[Out]#         Not(h__85),
#[Out]#         Not(h__86),
#[Out]#         Not(h__87),
#[Out]#         Not(h__88),
#[Out]#         Not(h__89),
#[Out]#         Not(h__90),
#[Out]#         Not(h__91),
#[Out]#         Not(h__92),
#[Out]#         Not(h__93),
#[Out]#         Not(h__94),
#[Out]#         Not(h__95),
#[Out]#         Not(h__96),
#[Out]#         Not(h__97),
#[Out]#         Not(h__98),
#[Out]#         Not(h__99),
#[Out]#         Not(h__100),
#[Out]#         Not(h__101),
#[Out]#         Not(h__102),
#[Out]#         Not(h__103),
#[Out]#         Not(h__104),
#[Out]#         Not(h__105),
#[Out]#         Not(h__106),
#[Out]#         Not(h__107),
#[Out]#         Not(h__108),
#[Out]#         Not(h__109),
#[Out]#         Not(h__110),
#[Out]#         Not(h__111),
#[Out]#         Not(h__112),
#[Out]#         Not(h__113),
#[Out]#         Not(h__114),
#[Out]#         Not(h__115),
#[Out]#         Not(h__116),
#[Out]#         Not(h__117),
#[Out]#         Not(h__118),
#[Out]#         Not(h__119),
#[Out]#         Not(h__120),
#[Out]#         Not(h__121),
#[Out]#         Not(h__122),
#[Out]#         Not(h__123),
#[Out]#         Not(h__124),
#[Out]#         Not(h__125),
#[Out]#         Not(h__126),
#[Out]#         Not(h__127),
#[Out]#         Not(h__128),
#[Out]#         Not(h__129),
#[Out]#         Not(h__130),
#[Out]#         Not(h__131),
#[Out]#         Not(h__132),
#[Out]#         Not(h__133),
#[Out]#         Not(h__134),
#[Out]#         Not(h__135),
#[Out]#         Not(h__136),
#[Out]#         Not(h__137),
#[Out]#         Not(h__138),
#[Out]#         Not(h__139),
#[Out]#         Not(h__140),
#[Out]#         Not(h__141),
#[Out]#         Not(h__142),
#[Out]#         Not(h__143),
#[Out]#         Not(h__144),
#[Out]#         Not(h__145),
#[Out]#         Not(h__146),
#[Out]#         Not(h__147),
#[Out]#         Not(h__148),
#[Out]#         Not(h__149),
#[Out]#         Not(h__150),
#[Out]#         Not(h__151),
#[Out]#         Not(h__152),
#[Out]#         Not(h__153),
#[Out]#         Not(h__154),
#[Out]#         Not(h__155),
#[Out]#         Not(h__156),
#[Out]#         Not(h__157),
#[Out]#         Not(h__158),
#[Out]#         Not(h__159),
#[Out]#         Not(h__160),
#[Out]#         Not(h__161),
#[Out]#         Not(h__162),
#[Out]#         Not(h__163),
#[Out]#         Not(h__164),
#[Out]#         Not(h__165)),
#[Out]#        161)
# Sun, 03 Dec 2017 23:40:21
solver.add(gEq6)
# Sun, 03 Dec 2017 23:40:31
%time solver.check()#[Out]# unsat
# CPU times: user 1h 37min 21s, sys: 10.6s, total: 1h 37min 31s
# Wall time: 1h 37min 32s 
